version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 0000
      MYSQL_DATABASE: kaddem
    ports:
      - "3307:3306"
    volumes:
      - db:/var/lib/mysql
    networks:
      - kaddem_network

  app-kaddem:
    image: espritt/khaddem:1.0.0

    restart: on-failure
    ports:
      - "8089:8089"
    environment:
      SPRING_APPLICATION_JSON: |
        {
          "spring.datasource.url": "jdbc:mysql://mysqldb:3306/kaddem?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC",
          "spring.datasource.username": "root",
          "spring.datasource.password":"0000",
          "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL5Dialect",
          "spring.jpa.hibernate.ddl-auto": "update"
        }
    depends_on:
      - mysqldb
    stdin_open: true
    tty: true
    networks:
      - kaddem_network

volumes:
  db:

networks:
  kaddem_network:
    driver: bridge
