version: "3.8"

services:
  mysql-db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"  # Allow empty password for root user
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: tpfoyerdb
      MYSQL_INNODB_FORCE_RECOVERY: 1
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root"]
      interval: 10s
      timeout: 20s
      retries: 10

  tp-foyer:
    depends_on:
      - mysql-db
    image: wafaalouane/tp-foyer:5.0.0
    restart: on-failure
    ports:
      - "8089:8089"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://mysql-db:3306/tpfoyerdb?createDatabaseIfNotExist=true&useSSL=false",
        "spring.datasource.username": "root",
        "spring.datasource.password": null,
        "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQLDialect",
        "spring.jpa.hibernate.ddl-auto": "update",
        "spring.liquibase.enabled": "true"
      }'
    stdin_open: true
    tty: true

volumes:
  mysql_data: