global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "jenkins"
    metrics_path: "/prometheus"
    static_configs:
      - targets: ["192.168.50.4:8080"]
  - job_name: "springboot-app"
    metrics_path: "/tpfoyer/actuator/prometheus"
    static_configs:
      - targets: ["192.168.50.4:8090"]
